# Meta Data for SEO

## Homepage
title = "Protein Report"
titleSeparator = "-"
titleAddition = "Protein economy news and industry platform"


twitterSite = "@Protein_Report"
twitterCreator = "@Protein_Report"

images = ["/favicon.png"]
ogLocale = "en_US"
titleHome = "Protein Report"

[options]
darkMode = true

# Images (@hyas/images)
[hyas_images]
  [hyas_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" # eager or lazy (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "75vw" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1680x720" for example
