# Hugo

title = "Protein Report"
description = "Advancing protein literacy for safer, more sustainable food systems"
images = ["/favicon.png"]

# SEO (@hyas/seo)

[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "images/logo/icon.png" # favicon.png (default)
    svgIcon = "images/logo/icon.svg" # favicon.svg (default)
    maskIcon = "images/logo/icon.svg" # mask-icon.svg (default)
    maskIconColor = "white" # white (default)
  [seo.schemas]
    type = "Organization" # Organization (default) or Person
    logo = "images/logo/logo.png" # Logo of Organization — images/favicon.png (default)
    name = "Protein Report" # Name of Organization or Person
    sameAs = ["https://github.com/proteinreport/proteinreport.org"] # E.g. ["https://github.com/gethyas/hyas", "https://fosstodon.org/@hyas"]
    images = ["images/logo/logo.png"] # ["images/cover.png"] (default)
    article = [] # Article sections
    newsArticle = [] # NewsArticle sections
    blogPosting = ["blog"] # BlogPosting sections
    product = [] # Product sections


# Images (@hyas/images)
[hyas_images]
  [hyas_images.landscape]
    normalize = "1360x765" # "1600x900" (default)
    lqip = "16x9" # "16x9" (default)
    widths = [480, 640, 800, 1024]
  [hyas_images.portrait]
    normalize = "765x1360" # "900x1600" (default)
    lqip = "9x16" # "9x16" (default)
    widths = [480, 640, 800, 1024]



titleSeparator = "-"
titleAddition = "Protein economy news and industry platform"

twitterSite = "@Protein_Report"
twitterCreator = "@Protein_Report"

ogLocale = "en_US"
titleHome = "Protein Report"

[options]
darkMode = true

