# Meta Data for SEO

## Homepage
title = "Protein Report"
titleSeparator = "|"
titleAddition = "advancing protein literacy"
description = "Reporting on the global protein economy. News, insight, analysis, and industry resources."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "proteinreport.org"
titleHome = "Protein Report"

## Twitter Cards
twitterSite = "@Protein_Report"
twitterCreator = "@Protein_Report"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Protein Report"
schemaAuthor = "Protein Report"
schemaAuthorTwitter = "https://twitter.com/Protein_Report"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/proteinreport/"
schemaAuthorGitHub = "https://github.com/proteinreport"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/Protein_Report"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/proteinreport/proteinreport.org"
schemaSection = "articles"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
#footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a #class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" #href=\"https://proteinreport.org/\">Protein Report</a>"
footer = "Copyright &copy; 2018-2022 Protein Report"

# Feed
copyRight = "Copyright (c) 2018-2022 Protein Report"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Welcome to the new proteinreport.org! The legacy version remains archived <a class=\"alert-link stretched-link\" href=\"https://proteinreport.org/\">here.</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/proteinreport/proteinreport.org"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
