backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  ########## Articles ##########
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    label_singular: "Article"
    folder: "content/en/articles" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    # slug: "{{slug}}/index.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "images", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
  ########## Newswire ##########
  - name: "newswire" # Used in routes, e.g., /admin/collections/blog
    label: "Newswire" # Used in the UI
    label_singular: "Press Release"
    folder: "content/en/newswire" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    # slug: "{{slug}}/index.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Company"
        name: "company"
        widget: "relation"
        collection: "directory"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - {label: "Company Name", name: "company_name", widget: "string"}
      - {label: "Company Link", name: "company_link", widget: "string"}
      - {label: "Image", name: "images", widget: "image"}
      - label: "Additional images"
        name: "additional_images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - label: "Proteins"
        name: "proteins"
        widget: "select"
        multiple: true
        options: ["Plant-Based", "Cell-Based", "Microbial", "Fungi", "Algae", "Animal", "Insect", "Molecular Farming"]
      - label: "Products"
        name: "products"
        widget: "select"
        multiple: true
        options: ["Meat", "Dairy", "Eggs", "Seafood", "Ingredients", "Pet Food", "Feed"]
      - label: "Topics"
        name: "topics"
        widget: "select"
        multiple: true
        options: ["Business", "Environment", "Policy", "Sci-Tech", "Health", "Culture"]
      - label: "Regions"
        name: "regions"
        widget: "select"
        multiple: true
        options: ["Africa", "Asia", "Europe", "International", "Latin America & Caribbean", "Middle East", "Oceania", "US & Canada"]
      - label: "Tech Segment"
        name: "tech_segment"
        widget: "select"
        multiple: true
        options: ["Agriculture & Plant Protein", "Fungiculture & Mycoprotein", "Algaculture & Algal Protein", "Cell Culture & Animal Protein", "Microbial & Precision Fermentation", "Molecular Farming", "Livestock & Animals"]
      - label: "Related Companies"
        name: "directory"
        widget: "relation"
        collection: "directory"
        multiple: true
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - {label: "Content", name: "body", widget: "markdown"}
  ########## Directory ##########
  - name: "directory" # Used in routes, e.g., /admin/collections/blog
    label: "Directory" # Used in the UI
    label_singular: "Directory Entry"
    folder: "content/en/directory" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    # slug: "{{slug}}/index.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "images", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Proteins"
        name: "proteins"
        widget: "select"
        multiple: true
        options: ["Plant-Based", "Cell-Based", "Microbial", "Fungi", "Algae", "Animal", "Insect", "Molecular Farming"]
      - label: "Products"
        name: "products"
        widget: "select"
        multiple: true
        options: ["Meat", "Dairy", "Eggs", "Seafood", "Ingredients", "Pet Food", "Feed"]
      - label: "Tech Segment"
        name: "tech_segment"
        widget: "select"
        multiple: true
        required: false
        options: ["Agriculture & Plant Protein", "Fungiculture & Mycoprotein", "Algaculture & Algal Protein", "Cell Culture & Animal Protein", "Microbial & Precision Fermentation", "Molecular Farming", "Livestock & Animals"]
      - label: ID
        name: id
        widget: ncw-id
        prefix: directory        # will generate post-124hfkjas
        timestamp: true     # will generate 1245119112-post-124hfkjas
        hint: This widget generate an unique read-only id
      - {label: "Content", name: "body", widget: "markdown"}